# Generated by Django 6.0.4 on 2026-04-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('e_date', models.DateField()),
                ('mobilenumber', models.IntegerField()),
                ('address', models.CharField(max_length=70)),
                ('landmark', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
