# Generated by Django 6.0.4 on 2026-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('babyshower', 'Babe Shower'), ('marriage', 'Marriage'), ('cultural', 'Cultural')], max_length=20)),
                ('image', models.URLField()),
                ('price', models.IntegerField()),
                ('offer_price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
